window.GOBRAX_DATA = {
  "spreadsheetId": "2PACX-1vSLoNqOJGDJe9FqcOzjsXNNnSGE3h_X04xFtkvi7K4X1fUkGAN968V_hDS9KJtH-lbBbkm-RSVC0Mjr",
  "generatedAt": "2026-04-14T19:14:17.573Z",
  "sheets": [
    {
      "name": "Março",
      "sourceName": "Março",
      "gid": "0",
      "order": 3,
      "type": null,
      "rows": [
        {
          "Frota": "243",
          "Placa": "LSE9F88",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 360",
          "Tração": "6X2",
          "Grupo de Veículos": "Operação Baker",
          "Nota Geral": "35",
          "Km Total": "59,34",
          "Velocidade Média": "8,95",
          "Consumo Total": "89",
          "Média computador de bordo": "0,67",
          "Odômetro": "746626,42",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "9",
          "Freadas a cada 100 km": "9",
          "Total Motor Ligado Parado": "16:27:10",
          "% Total Motor Ligado Parado": "71,29%",
          "Tempo em Movimento": "06:37:36",
          "% Tempo em Movimento": "28,71%",
          "Faixa Verde": "03:40:31",
          "% Faixa Verde": "55,47%",
          "Início da faixa verde": "03:28:31",
          "% Início da faixa verde": "52,44%",
          "Final da faixa verde": "00:12:01",
          "% Final da faixa verde": "3,02%",
          "Acelerando acima do verde": "00:12:30",
          "% Acelerando acima do verde": "3,14%",
          "Aproveitamento de Embalo": "04:00:07",
          "% Aproveitamento de Embalo": "60,39%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "01:01:22",
          "% Freio Motor": "15,44%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:02:00",
          "% Eco-Roll/I-Roll": "0,50%",
          "Uso do Pedal Ideal": "04:06:40",
          "% Pedal Ideal": "98,60%",
          "Uso do Pedal Atenção": "00:02:00",
          "% Pedal Atenção": "0,80%",
          "Uso do Pedal Critico": "00:01:30",
          "% Pedal Critico": "0,60%"
        },
        {
          "Frota": "222",
          "Placa": "KOW6F24",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/24.250 CNC",
          "Tração": "6X2",
          "Grupo de Veículos": "OPERAÇÃO MUNCK",
          "Nota Geral": "77",
          "Km Total": "678,76",
          "Velocidade Média": "24,49",
          "Consumo Total": "234,5",
          "Média computador de bordo": "2,89",
          "Odômetro": "234204,32",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "3",
          "Freadas a cada 100 km": "0,4",
          "Total Motor Ligado Parado": "26:24:46",
          "% Total Motor Ligado Parado": "48,80%",
          "Tempo em Movimento": "27:42:49",
          "% Tempo em Movimento": "51,20%",
          "Faixa Verde": "27:09:19",
          "% Faixa Verde": "97,99%",
          "Início da faixa verde": "25:01:12",
          "% Início da faixa verde": "90,28%",
          "Final da faixa verde": "02:08:07",
          "% Final da faixa verde": "7,71%",
          "Acelerando acima do verde": "00:28:00",
          "% Acelerando acima do verde": "1,68%",
          "Aproveitamento de Embalo": "11:20:12",
          "% Aproveitamento de Embalo": "40,91%",
          "Excesso de Velocidade": "00:03:00",
          "% Excesso de Velocidade": "0,18%",
          "Freio Motor": "00:06:00",
          "% Freio Motor": "0,36%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:01:01",
          "% Eco-Roll/I-Roll": "0,06%",
          "Uso do Pedal Ideal": "14:36:22",
          "% Pedal Ideal": "87,16%",
          "Uso do Pedal Atenção": "01:20:40",
          "% Pedal Atenção": "8,02%",
          "Uso do Pedal Critico": "00:48:27",
          "% Pedal Critico": "4,82%"
        },
        {
          "Frota": "245",
          "Placa": "KWW9A65",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 360",
          "Tração": "6X2",
          "Grupo de Veículos": "Operação Baker",
          "Nota Geral": "25",
          "Km Total": "0",
          "Velocidade Média": "0",
          "Consumo Total": "0",
          "Média computador de bordo": "0",
          "Odômetro": "0",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "0",
          "Freadas a cada 100 km": "0",
          "Total Motor Ligado Parado": "00:00:00",
          "% Total Motor Ligado Parado": "0,00%",
          "Tempo em Movimento": "00:00:00",
          "% Tempo em Movimento": "0,00%",
          "Faixa Verde": "00:00:00",
          "% Faixa Verde": "0,00%",
          "Início da faixa verde": "00:00:00",
          "% Início da faixa verde": "0,00%",
          "Final da faixa verde": "00:00:00",
          "% Final da faixa verde": "0,00%",
          "Acelerando acima do verde": "00:00:00",
          "% Acelerando acima do verde": "0,00%",
          "Aproveitamento de Embalo": "00:00:00",
          "% Aproveitamento de Embalo": "0,00%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:00:00",
          "% Freio Motor": "0,00%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:00:00",
          "% Eco-Roll/I-Roll": "0,00%",
          "Uso do Pedal Ideal": "00:00:00",
          "% Pedal Ideal": "0,00%",
          "Uso do Pedal Atenção": "00:00:00",
          "% Pedal Atenção": "0,00%",
          "Uso do Pedal Critico": "00:00:00",
          "% Pedal Critico": "0,00%"
        },
        {
          "Frota": "244",
          "Placa": "KRH8082",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 360",
          "Tração": "6X2",
          "Grupo de Veículos": "Operação Baker",
          "Nota Geral": "64",
          "Km Total": "1681,19",
          "Velocidade Média": "32,91",
          "Consumo Total": "783,5",
          "Média computador de bordo": "2,15",
          "Odômetro": "597756,92",
          "Freadas em Alta velocidade": "15",
          "Freadas totais": "405",
          "Freadas a cada 100 km": "24,1",
          "Total Motor Ligado Parado": "16:45:19",
          "% Total Motor Ligado Parado": "24,70%",
          "Tempo em Movimento": "51:04:48",
          "% Tempo em Movimento": "75,30%",
          "Faixa Verde": "50:42:58",
          "% Faixa Verde": "99,29%",
          "Início da faixa verde": "45:35:55",
          "% Início da faixa verde": "89,27%",
          "Final da faixa verde": "05:07:04",
          "% Final da faixa verde": "10,02%",
          "Acelerando acima do verde": "00:18:49",
          "% Acelerando acima do verde": "0,61%",
          "Aproveitamento de Embalo": "15:56:40",
          "% Aproveitamento de Embalo": "31,22%",
          "Excesso de Velocidade": "00:55:31",
          "% Excesso de Velocidade": "1,81%",
          "Freio Motor": "00:03:00",
          "% Freio Motor": "0,10%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:17:31",
          "% Eco-Roll/I-Roll": "0,57%",
          "Uso do Pedal Ideal": "30:17:34",
          "% Pedal Ideal": "83,24%",
          "Uso do Pedal Atenção": "03:57:55",
          "% Pedal Atenção": "10,90%",
          "Uso do Pedal Critico": "02:08:04",
          "% Pedal Critico": "5,87%"
        },
        {
          "Frota": "246",
          "Placa": "LSE9591",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 360",
          "Tração": "6X2",
          "Grupo de Veículos": "Operação Baker",
          "Nota Geral": "47",
          "Km Total": "2271,24",
          "Velocidade Média": "39,8",
          "Consumo Total": "894",
          "Média computador de bordo": "2,54",
          "Odômetro": "753151,69",
          "Freadas em Alta velocidade": "1",
          "Freadas totais": "295",
          "Freadas a cada 100 km": "13",
          "Total Motor Ligado Parado": "06:03:37",
          "% Total Motor Ligado Parado": "9,60%",
          "Tempo em Movimento": "57:03:54",
          "% Tempo em Movimento": "90,40%",
          "Faixa Verde": "56:45:49",
          "% Faixa Verde": "99,47%",
          "Início da faixa verde": "54:11:07",
          "% Início da faixa verde": "94,95%",
          "Final da faixa verde": "02:34:42",
          "% Final da faixa verde": "4,52%",
          "Acelerando acima do verde": "00:20:19",
          "% Acelerando acima do verde": "0,59%",
          "Aproveitamento de Embalo": "14:21:46",
          "% Aproveitamento de Embalo": "25,17%",
          "Excesso de Velocidade": "00:12:03",
          "% Excesso de Velocidade": "0,35%",
          "Freio Motor": "00:03:30",
          "% Freio Motor": "0,10%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:37:45",
          "% Eco-Roll/I-Roll": "1,10%",
          "Uso do Pedal Ideal": "35:08:45",
          "% Pedal Ideal": "80,74%",
          "Uso do Pedal Atenção": "04:33:19",
          "% Pedal Atenção": "10,47%",
          "Uso do Pedal Critico": "03:49:43",
          "% Pedal Critico": "8,80%"
        },
        {
          "Frota": "177",
          "Placa": "KZK2E10",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/R 420",
          "Tração": "6X4",
          "Grupo de Veículos": "Operação Redex",
          "Nota Geral": "85",
          "Km Total": "0,52",
          "Velocidade Média": "2,69",
          "Consumo Total": "1,5",
          "Média computador de bordo": "0,34",
          "Odômetro": "778882,81",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "0",
          "Freadas a cada 100 km": "0",
          "Total Motor Ligado Parado": "00:08:31",
          "% Total Motor Ligado Parado": "42,60%",
          "Tempo em Movimento": "00:11:28",
          "% Tempo em Movimento": "57,40%",
          "Faixa Verde": "00:11:28",
          "% Faixa Verde": "100,00%",
          "Início da faixa verde": "00:11:28",
          "% Início da faixa verde": "100,00%",
          "Final da faixa verde": "00:00:00",
          "% Final da faixa verde": "0,00%",
          "Acelerando acima do verde": "00:00:00",
          "% Acelerando acima do verde": "0,00%",
          "Aproveitamento de Embalo": "00:07:28",
          "% Aproveitamento de Embalo": "65,16%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:00:00",
          "% Freio Motor": "0,00%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:00:00",
          "% Eco-Roll/I-Roll": "0,00%",
          "Uso do Pedal Ideal": "00:04:00",
          "% Pedal Ideal": "100,00%",
          "Uso do Pedal Atenção": "00:00:00",
          "% Pedal Atenção": "0,00%",
          "Uso do Pedal Critico": "00:00:00",
          "% Pedal Critico": "0,00%"
        },
        {
          "Frota": "150",
          "Placa": "KNM9F91",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/G 420",
          "Tração": "6X4",
          "Grupo de Veículos": "Operação Redex",
          "Nota Geral": "53",
          "Km Total": "1946,81",
          "Velocidade Média": "27,22",
          "Consumo Total": "1261",
          "Média computador de bordo": "1,54",
          "Odômetro": "924441,47",
          "Freadas em Alta velocidade": "2",
          "Freadas totais": "357",
          "Freadas a cada 100 km": "18,3",
          "Total Motor Ligado Parado": "34:38:45",
          "% Total Motor Ligado Parado": "32,63%",
          "Tempo em Movimento": "71:31:58",
          "% Tempo em Movimento": "67,37%",
          "Faixa Verde": "70:24:07",
          "% Faixa Verde": "98,42%",
          "Início da faixa verde": "62:24:25",
          "% Início da faixa verde": "87,24%",
          "Final da faixa verde": "07:59:42",
          "% Final da faixa verde": "11,18%",
          "Acelerando acima do verde": "00:53:30",
          "% Acelerando acima do verde": "1,25%",
          "Aproveitamento de Embalo": "24:30:37",
          "% Aproveitamento de Embalo": "34,26%",
          "Excesso de Velocidade": "00:41:31",
          "% Excesso de Velocidade": "0,97%",
          "Freio Motor": "00:00:00",
          "% Freio Motor": "0,00%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "01:10:01",
          "% Eco-Roll/I-Roll": "1,63%",
          "Uso do Pedal Ideal": "33:50:01",
          "% Pedal Ideal": "70,56%",
          "Uso do Pedal Atenção": "03:22:09",
          "% Pedal Atenção": "7,03%",
          "Uso do Pedal Critico": "10:44:51",
          "% Pedal Critico": "22,41%"
        },
        {
          "Frota": "190",
          "Placa": "KVJ9G66",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/R 420",
          "Tração": "6X4",
          "Grupo de Veículos": "Operação Redex",
          "Nota Geral": "83",
          "Km Total": "565,77",
          "Velocidade Média": "22,34",
          "Consumo Total": "291,5",
          "Média computador de bordo": "1,94",
          "Odômetro": "749952,53",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "101",
          "Freadas a cada 100 km": "17,9",
          "Total Motor Ligado Parado": "11:23:52",
          "% Total Motor Ligado Parado": "31,04%",
          "Tempo em Movimento": "25:19:28",
          "% Tempo em Movimento": "68,96%",
          "Faixa Verde": "25:12:27",
          "% Faixa Verde": "99,54%",
          "Início da faixa verde": "24:06:55",
          "% Início da faixa verde": "95,23%",
          "Final da faixa verde": "01:05:31",
          "% Final da faixa verde": "4,31%",
          "Acelerando acima do verde": "00:06:31",
          "% Acelerando acima do verde": "0,43%",
          "Aproveitamento de Embalo": "10:03:42",
          "% Aproveitamento de Embalo": "39,73%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:00:30",
          "% Freio Motor": "0,03%",
          "Piloto Automático": "01:04:31",
          "% Piloto Automático": "4,25%",
          "Eco-Roll/I-Roll": "00:26:58",
          "% Eco-Roll/I-Roll": "1,77%",
          "Uso do Pedal Ideal": "12:59:49",
          "% Pedal Ideal": "87,64%",
          "Uso do Pedal Atenção": "00:49:58",
          "% Pedal Atenção": "5,62%",
          "Uso do Pedal Critico": "01:00:03",
          "% Pedal Critico": "6,75%"
        },
        {
          "Frota": "171",
          "Placa": "LKZ8C47",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 310",
          "Tração": "4x2",
          "Grupo de Veículos": "Operação Vazio",
          "Nota Geral": "25",
          "Km Total": "0",
          "Velocidade Média": "0",
          "Consumo Total": "0",
          "Média computador de bordo": "0",
          "Odômetro": "652489,6",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "0",
          "Freadas a cada 100 km": "0",
          "Total Motor Ligado Parado": "00:00:00",
          "% Total Motor Ligado Parado": "0,00%",
          "Tempo em Movimento": "00:00:00",
          "% Tempo em Movimento": "0,00%",
          "Faixa Verde": "00:00:00",
          "% Faixa Verde": "0,00%",
          "Início da faixa verde": "00:00:00",
          "% Início da faixa verde": "0,00%",
          "Final da faixa verde": "00:00:00",
          "% Final da faixa verde": "0,00%",
          "Acelerando acima do verde": "00:00:00",
          "% Acelerando acima do verde": "0,00%",
          "Aproveitamento de Embalo": "00:00:00",
          "% Aproveitamento de Embalo": "0,00%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:00:00",
          "% Freio Motor": "0,00%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:00:00",
          "% Eco-Roll/I-Roll": "0,00%",
          "Uso do Pedal Ideal": "00:00:00",
          "% Pedal Ideal": "0,00%",
          "Uso do Pedal Atenção": "00:00:00",
          "% Pedal Atenção": "0,00%",
          "Uso do Pedal Critico": "00:00:00",
          "% Pedal Critico": "0,00%"
        },
        {
          "Frota": "188",
          "Placa": "LPT9A89",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/R 420",
          "Tração": "6X4",
          "Grupo de Veículos": "Operação Redex",
          "Nota Geral": "74",
          "Km Total": "3807,71",
          "Velocidade Média": "24,71",
          "Consumo Total": "1925,5",
          "Média computador de bordo": "1,98",
          "Odômetro": "828324,77",
          "Freadas em Alta velocidade": "1",
          "Freadas totais": "559",
          "Freadas a cada 100 km": "14,7",
          "Total Motor Ligado Parado": "38:00:55",
          "% Total Motor Ligado Parado": "19,79%",
          "Tempo em Movimento": "154:05:24",
          "% Tempo em Movimento": "80,21%",
          "Faixa Verde": "153:35:21",
          "% Faixa Verde": "99,67%",
          "Início da faixa verde": "143:15:07",
          "% Início da faixa verde": "92,97%",
          "Final da faixa verde": "10:20:13",
          "% Final da faixa verde": "6,71%",
          "Acelerando acima do verde": "00:07:04",
          "% Acelerando acima do verde": "0,08%",
          "Aproveitamento de Embalo": "51:45:19",
          "% Aproveitamento de Embalo": "33,59%",
          "Excesso de Velocidade": "00:17:01",
          "% Excesso de Velocidade": "0,18%",
          "Freio Motor": "00:09:58",
          "% Freio Motor": "0,11%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "02:27:30",
          "% Eco-Roll/I-Roll": "1,60%",
          "Uso do Pedal Ideal": "91:47:58",
          "% Pedal Ideal": "89,12%",
          "Uso do Pedal Atenção": "05:36:52",
          "% Pedal Atenção": "5,45%",
          "Uso do Pedal Critico": "05:35:16",
          "% Pedal Critico": "5,43%"
        },
        {
          "Frota": "181",
          "Placa": "LLI2F10",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/19.320",
          "Tração": "4x2",
          "Grupo de Veículos": "Operação Vazio",
          "Nota Geral": "84",
          "Km Total": "1679,8",
          "Velocidade Média": "25,59",
          "Consumo Total": "446,5",
          "Média computador de bordo": "3,76",
          "Odômetro": "483179,59",
          "Freadas em Alta velocidade": "2",
          "Freadas totais": "183",
          "Freadas a cada 100 km": "10,9",
          "Total Motor Ligado Parado": "19:22:43",
          "% Total Motor Ligado Parado": "22,78%",
          "Tempo em Movimento": "65:40:19",
          "% Tempo em Movimento": "77,22%",
          "Faixa Verde": "65:30:49",
          "% Faixa Verde": "99,76%",
          "Início da faixa verde": "62:22:37",
          "% Início da faixa verde": "94,98%",
          "Final da faixa verde": "03:08:12",
          "% Final da faixa verde": "4,78%",
          "Acelerando acima do verde": "00:09:30",
          "% Acelerando acima do verde": "0,24%",
          "Aproveitamento de Embalo": "34:11:28",
          "% Aproveitamento de Embalo": "52,06%",
          "Excesso de Velocidade": "01:35:06",
          "% Excesso de Velocidade": "2,41%",
          "Freio Motor": "00:02:30",
          "% Freio Motor": "0,06%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:08:28",
          "% Eco-Roll/I-Roll": "0,22%",
          "Uso do Pedal Ideal": "32:11:55",
          "% Pedal Ideal": "97,06%",
          "Uso do Pedal Atenção": "00:39:01",
          "% Pedal Atenção": "1,96%",
          "Uso do Pedal Critico": "00:19:31",
          "% Pedal Critico": "0,98%"
        },
        {
          "Frota": "227",
          "Placa": "LLT6B06",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/19.330 CTC",
          "Tração": "4x2",
          "Grupo de Veículos": "Operação Vazio",
          "Nota Geral": "75",
          "Km Total": "1138,83",
          "Velocidade Média": "25,32",
          "Consumo Total": "404,16",
          "Média computador de bordo": "2,82",
          "Odômetro": "355079,26",
          "Freadas em Alta velocidade": "4",
          "Freadas totais": "248",
          "Freadas a cada 100 km": "21,8",
          "Total Motor Ligado Parado": "15:47:13",
          "% Total Motor Ligado Parado": "25,98%",
          "Tempo em Movimento": "44:58:34",
          "% Tempo em Movimento": "74,02%",
          "Faixa Verde": "42:56:48",
          "% Faixa Verde": "95,49%",
          "Início da faixa verde": "39:04:18",
          "% Início da faixa verde": "86,87%",
          "Final da faixa verde": "03:52:30",
          "% Final da faixa verde": "8,62%",
          "Acelerando acima do verde": "01:49:01",
          "% Acelerando acima do verde": "4,04%",
          "Aproveitamento de Embalo": "21:44:25",
          "% Aproveitamento de Embalo": "48,34%",
          "Excesso de Velocidade": "02:30:00",
          "% Excesso de Velocidade": "5,56%",
          "Freio Motor": "00:16:00",
          "% Freio Motor": "0,59%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:04:45",
          "% Eco-Roll/I-Roll": "0,18%",
          "Uso do Pedal Ideal": "21:42:52",
          "% Pedal Ideal": "87,65%",
          "Uso do Pedal Atenção": "00:53:28",
          "% Pedal Atenção": "3,60%",
          "Uso do Pedal Critico": "02:10:01",
          "% Pedal Critico": "8,75%"
        },
        {
          "Frota": "229",
          "Placa": "LLT6B02",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/19.330 CTC",
          "Tração": "4x2",
          "Grupo de Veículos": "Operação Vazio",
          "Nota Geral": "35",
          "Km Total": "2474,5",
          "Velocidade Média": "24,5",
          "Consumo Total": "768",
          "Média computador de bordo": "3,22",
          "Odômetro": "1263441,4",
          "Freadas em Alta velocidade": "449",
          "Freadas totais": "4641",
          "Freadas a cada 100 km": "187,6",
          "Total Motor Ligado Parado": "28:15:00",
          "% Total Motor Ligado Parado": "21,86%",
          "Tempo em Movimento": "100:58:48",
          "% Tempo em Movimento": "78,14%",
          "Faixa Verde": "75:49:36",
          "% Faixa Verde": "75,09%",
          "Início da faixa verde": "61:23:19",
          "% Início da faixa verde": "60,79%",
          "Final da faixa verde": "14:26:16",
          "% Final da faixa verde": "14,30%",
          "Acelerando acima do verde": "15:39:54",
          "% Acelerando acima do verde": "15,51%",
          "Aproveitamento de Embalo": "62:55:07",
          "% Aproveitamento de Embalo": "62,31%",
          "Excesso de Velocidade": "03:01:10",
          "% Excesso de Velocidade": "2,99%",
          "Freio Motor": "07:07:34",
          "% Freio Motor": "7,06%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:45:28",
          "% Eco-Roll/I-Roll": "0,75%",
          "Uso do Pedal Ideal": "45:06:45",
          "% Pedal Ideal": "98,94%",
          "Uso do Pedal Atenção": "00:22:00",
          "% Pedal Atenção": "0,80%",
          "Uso do Pedal Critico": "00:07:01",
          "% Pedal Critico": "0,26%"
        },
        {
          "Frota": "231",
          "Placa": "LRA1E88",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/R 440",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "85",
          "Km Total": "71,15",
          "Velocidade Média": "33,59",
          "Consumo Total": "38,63",
          "Média computador de bordo": "1,84",
          "Odômetro": "967678,39",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "6",
          "Freadas a cada 100 km": "6",
          "Total Motor Ligado Parado": "05:07:33",
          "% Total Motor Ligado Parado": "70,76%",
          "Tempo em Movimento": "02:07:04",
          "% Tempo em Movimento": "29,24%",
          "Faixa Verde": "02:10:34",
          "% Faixa Verde": "100,00%",
          "Início da faixa verde": "02:07:36",
          "% Início da faixa verde": "100,00%",
          "Final da faixa verde": "00:02:58",
          "% Final da faixa verde": "2,34%",
          "Acelerando acima do verde": "00:00:00",
          "% Acelerando acima do verde": "0,00%",
          "Aproveitamento de Embalo": "00:48:28",
          "% Aproveitamento de Embalo": "38,14%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:01:28",
          "% Freio Motor": "1,16%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:00:30",
          "% Eco-Roll/I-Roll": "0,39%",
          "Uso do Pedal Ideal": "01:16:34",
          "% Pedal Ideal": "98,72%",
          "Uso do Pedal Atenção": "00:00:30",
          "% Pedal Atenção": "0,64%",
          "Uso do Pedal Critico": "00:00:30",
          "% Pedal Critico": "0,64%"
        },
        {
          "Frota": "230",
          "Placa": "LQN4F96",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/19.330 CTC",
          "Tração": "4x2",
          "Grupo de Veículos": "Operação Vazio",
          "Nota Geral": "48",
          "Km Total": "1961,61",
          "Velocidade Média": "21,73",
          "Consumo Total": "701",
          "Média computador de bordo": "2,8",
          "Odômetro": "465942,08",
          "Freadas em Alta velocidade": "571",
          "Freadas totais": "3486",
          "Freadas a cada 100 km": "177,7",
          "Total Motor Ligado Parado": "36:24:40",
          "% Total Motor Ligado Parado": "28,74%",
          "Tempo em Movimento": "90:17:22",
          "% Tempo em Movimento": "71,26%",
          "Faixa Verde": "88:12:36",
          "% Faixa Verde": "97,70%",
          "Início da faixa verde": "69:51:18",
          "% Início da faixa verde": "77,37%",
          "Final da faixa verde": "18:21:18",
          "% Final da faixa verde": "20,33%",
          "Acelerando acima do verde": "01:57:46",
          "% Acelerando acima do verde": "2,17%",
          "Aproveitamento de Embalo": "32:00:52",
          "% Aproveitamento de Embalo": "35,46%",
          "Excesso de Velocidade": "03:55:04",
          "% Excesso de Velocidade": "4,34%",
          "Freio Motor": "00:09:30",
          "% Freio Motor": "0,18%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:58:03",
          "% Eco-Roll/I-Roll": "1,07%",
          "Uso do Pedal Ideal": "58:38:19",
          "% Pedal Ideal": "97,32%",
          "Uso do Pedal Atenção": "00:51:01",
          "% Pedal Atenção": "1,41%",
          "Uso do Pedal Critico": "00:46:01",
          "% Pedal Critico": "1,27%"
        },
        {
          "Frota": "247",
          "Placa": "LSF8B12",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/R 480",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "25",
          "Km Total": "0",
          "Velocidade Média": "0",
          "Consumo Total": "0",
          "Média computador de bordo": "0",
          "Odômetro": "0",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "0",
          "Freadas a cada 100 km": "0",
          "Total Motor Ligado Parado": "00:00:00",
          "% Total Motor Ligado Parado": "0,00%",
          "Tempo em Movimento": "00:00:00",
          "% Tempo em Movimento": "0,00%",
          "Faixa Verde": "00:00:00",
          "% Faixa Verde": "0,00%",
          "Início da faixa verde": "00:00:00",
          "% Início da faixa verde": "0,00%",
          "Final da faixa verde": "00:00:00",
          "% Final da faixa verde": "0,00%",
          "Acelerando acima do verde": "00:00:00",
          "% Acelerando acima do verde": "0,00%",
          "Aproveitamento de Embalo": "00:00:00",
          "% Aproveitamento de Embalo": "0,00%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:00:00",
          "% Freio Motor": "0,00%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:00:00",
          "% Eco-Roll/I-Roll": "0,00%",
          "Uso do Pedal Ideal": "00:00:00",
          "% Pedal Ideal": "0,00%",
          "Uso do Pedal Atenção": "00:00:00",
          "% Pedal Atenção": "0,00%",
          "Uso do Pedal Critico": "00:00:00",
          "% Pedal Critico": "0,00%"
        },
        {
          "Frota": "236",
          "Placa": "KWC5138",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 360",
          "Tração": "6X2",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "75",
          "Km Total": "1528,2",
          "Velocidade Média": "23,64",
          "Consumo Total": "661",
          "Média computador de bordo": "2,31",
          "Odômetro": "802287,36",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "301",
          "Freadas a cada 100 km": "19,7",
          "Total Motor Ligado Parado": "40:09:52",
          "% Total Motor Ligado Parado": "38,32%",
          "Tempo em Movimento": "64:38:31",
          "% Tempo em Movimento": "61,68%",
          "Faixa Verde": "65:29:58",
          "% Faixa Verde": "100,00%",
          "Início da faixa verde": "60:29:36",
          "% Início da faixa verde": "93,58%",
          "Final da faixa verde": "05:00:22",
          "% Final da faixa verde": "7,74%",
          "Acelerando acima do verde": "02:05:06",
          "% Acelerando acima do verde": "3,23%",
          "Aproveitamento de Embalo": "24:37:07",
          "% Aproveitamento de Embalo": "38,08%",
          "Excesso de Velocidade": "00:09:30",
          "% Excesso de Velocidade": "0,24%",
          "Freio Motor": "00:13:07",
          "% Freio Motor": "0,34%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "01:22:48",
          "% Eco-Roll/I-Roll": "2,13%",
          "Uso do Pedal Ideal": "38:52:55",
          "% Pedal Ideal": "88,35%",
          "Uso do Pedal Atenção": "01:57:09",
          "% Pedal Atenção": "4,44%",
          "Uso do Pedal Critico": "03:10:27",
          "% Pedal Critico": "7,21%"
        },
        {
          "Frota": "285",
          "Placa": "TTX5D85",
          "Marca": "DAF",
          "Modelo": "XF FTS EURO 6",
          "Tração": "6X2",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "69",
          "Km Total": "4125,57",
          "Velocidade Média": "36,12",
          "Consumo Total": "1757",
          "Média computador de bordo": "2,35",
          "Odômetro": "13640,62",
          "Freadas em Alta velocidade": "4",
          "Freadas totais": "370",
          "Freadas a cada 100 km": "9",
          "Total Motor Ligado Parado": "28:03:49",
          "% Total Motor Ligado Parado": "19,72%",
          "Tempo em Movimento": "114:13:01",
          "% Tempo em Movimento": "80,28%",
          "Faixa Verde": "111:46:34",
          "% Faixa Verde": "97,86%",
          "Início da faixa verde": "107:56:43",
          "% Início da faixa verde": "94,51%",
          "Final da faixa verde": "03:49:51",
          "% Final da faixa verde": "3,35%",
          "Acelerando acima do verde": "00:32:22",
          "% Acelerando acima do verde": "0,47%",
          "Aproveitamento de Embalo": "37:41:10",
          "% Aproveitamento de Embalo": "33,00%",
          "Excesso de Velocidade": "00:11:30",
          "% Excesso de Velocidade": "0,17%",
          "Freio Motor": "01:54:04",
          "% Freio Motor": "1,66%",
          "Piloto Automático": "05:48:01",
          "% Piloto Automático": "5,08%",
          "Eco-Roll/I-Roll": "01:10:31",
          "% Eco-Roll/I-Roll": "1,03%",
          "Uso do Pedal Ideal": "58:15:06",
          "% Pedal Ideal": "81,32%",
          "Uso do Pedal Atenção": "03:50:34",
          "% Pedal Atenção": "5,36%",
          "Uso do Pedal Critico": "09:32:31",
          "% Pedal Critico": "13,32%"
        },
        {
          "Frota": "284",
          "Placa": "TTC9B61",
          "Marca": "DAF",
          "Modelo": "XF FTS EURO 6",
          "Tração": "6X2",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "60",
          "Km Total": "8670,67",
          "Velocidade Média": "46,18",
          "Consumo Total": "3969,5",
          "Média computador de bordo": "2,18",
          "Odômetro": "22143,62",
          "Freadas em Alta velocidade": "56",
          "Freadas totais": "621",
          "Freadas a cada 100 km": "7,2",
          "Total Motor Ligado Parado": "43:51:12",
          "% Total Motor Ligado Parado": "18,94%",
          "Tempo em Movimento": "187:44:18",
          "% Tempo em Movimento": "81,06%",
          "Faixa Verde": "178:51:28",
          "% Faixa Verde": "95,27%",
          "Início da faixa verde": "164:59:51",
          "% Início da faixa verde": "87,89%",
          "Final da faixa verde": "13:51:37",
          "% Final da faixa verde": "7,38%",
          "Acelerando acima do verde": "02:07:27",
          "% Acelerando acima do verde": "1,13%",
          "Aproveitamento de Embalo": "70:35:12",
          "% Aproveitamento de Embalo": "37,60%",
          "Excesso de Velocidade": "06:52:04",
          "% Excesso de Velocidade": "3,66%",
          "Freio Motor": "06:47:22",
          "% Freio Motor": "3,62%",
          "Piloto Automático": "02:45:03",
          "% Piloto Automático": "1,47%",
          "Eco-Roll/I-Roll": "05:59:04",
          "% Eco-Roll/I-Roll": "3,19%",
          "Uso do Pedal Ideal": "70:01:19",
          "% Pedal Ideal": "60,25%",
          "Uso do Pedal Atenção": "10:20:25",
          "% Pedal Atenção": "8,90%",
          "Uso do Pedal Critico": "35:51:56",
          "% Pedal Critico": "30,86%"
        },
        {
          "Frota": "286",
          "Placa": "TTU6J59",
          "Marca": "DAF",
          "Modelo": "XF FTS EURO 6",
          "Tração": "6X2",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "67",
          "Km Total": "1873,9",
          "Velocidade Média": "37,26",
          "Consumo Total": "673",
          "Média computador de bordo": "2,78",
          "Odômetro": "12936,53",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "210",
          "Freadas a cada 100 km": "11,2",
          "Total Motor Ligado Parado": "04:30:31",
          "% Total Motor Ligado Parado": "8,23%",
          "Tempo em Movimento": "50:17:22",
          "% Tempo em Movimento": "91,77%",
          "Faixa Verde": "50:08:52",
          "% Faixa Verde": "99,72%",
          "Início da faixa verde": "49:13:03",
          "% Início da faixa verde": "97,87%",
          "Final da faixa verde": "00:55:49",
          "% Final da faixa verde": "1,85%",
          "Acelerando acima do verde": "00:03:00",
          "% Acelerando acima do verde": "0,10%",
          "Aproveitamento de Embalo": "15:50:51",
          "% Aproveitamento de Embalo": "31,51%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:06:31",
          "% Freio Motor": "0,22%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:19:00",
          "% Eco-Roll/I-Roll": "0,63%",
          "Uso do Pedal Ideal": "32:36:07",
          "% Pedal Ideal": "92,80%",
          "Uso do Pedal Atenção": "01:21:01",
          "% Pedal Atenção": "3,84%",
          "Uso do Pedal Critico": "01:10:52",
          "% Pedal Critico": "3,36%"
        },
        {
          "Frota": "288",
          "Placa": "TUL2J59",
          "Marca": "DAF",
          "Modelo": "XF FTS EURO 6",
          "Tração": "6X2",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "42",
          "Km Total": "4845,46",
          "Velocidade Média": "50,07",
          "Consumo Total": "2173,5",
          "Média computador de bordo": "2,23",
          "Odômetro": "13218,91",
          "Freadas em Alta velocidade": "17",
          "Freadas totais": "232",
          "Freadas a cada 100 km": "4,8",
          "Total Motor Ligado Parado": "23:35:25",
          "% Total Motor Ligado Parado": "19,59%",
          "Tempo em Movimento": "96:50:49",
          "% Tempo em Movimento": "80,41%",
          "Faixa Verde": "92:34:03",
          "% Faixa Verde": "95,58%",
          "Início da faixa verde": "86:27:04",
          "% Início da faixa verde": "89,27%",
          "Final da faixa verde": "06:06:58",
          "% Final da faixa verde": "6,32%",
          "Acelerando acima do verde": "00:24:49",
          "% Acelerando acima do verde": "0,43%",
          "Aproveitamento de Embalo": "28:59:55",
          "% Aproveitamento de Embalo": "29,94%",
          "Excesso de Velocidade": "00:17:00",
          "% Excesso de Velocidade": "0,29%",
          "Freio Motor": "03:52:57",
          "% Freio Motor": "4,01%",
          "Piloto Automático": "04:07:03",
          "% Piloto Automático": "4,25%",
          "Eco-Roll/I-Roll": "02:30:37",
          "% Eco-Roll/I-Roll": "2,59%",
          "Uso do Pedal Ideal": "43:22:49",
          "% Pedal Ideal": "67,46%",
          "Uso do Pedal Atenção": "04:44:40",
          "% Pedal Atenção": "7,38%",
          "Uso do Pedal Critico": "16:10:36",
          "% Pedal Critico": "25,16%"
        },
        {
          "Frota": "287",
          "Placa": "TTY5A07",
          "Marca": "DAF",
          "Modelo": "XF FTS EURO 6",
          "Tração": "6X2",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "75",
          "Km Total": "6999,29",
          "Velocidade Média": "39,02",
          "Consumo Total": "3151",
          "Média computador de bordo": "2,22",
          "Odômetro": "18862,42",
          "Freadas em Alta velocidade": "18",
          "Freadas totais": "421",
          "Freadas a cada 100 km": "6",
          "Total Motor Ligado Parado": "65:14:07",
          "% Total Motor Ligado Parado": "26,66%",
          "Tempo em Movimento": "179:25:28",
          "% Tempo em Movimento": "73,34%",
          "Faixa Verde": "170:54:04",
          "% Faixa Verde": "95,25%",
          "Início da faixa verde": "161:25:25",
          "% Início da faixa verde": "89,97%",
          "Final da faixa verde": "09:28:39",
          "% Final da faixa verde": "5,28%",
          "Acelerando acima do verde": "02:04:46",
          "% Acelerando acima do verde": "1,16%",
          "Aproveitamento de Embalo": "67:30:13",
          "% Aproveitamento de Embalo": "37,62%",
          "Excesso de Velocidade": "00:54:30",
          "% Excesso de Velocidade": "0,51%",
          "Freio Motor": "06:27:37",
          "% Freio Motor": "3,60%",
          "Piloto Automático": "05:01:09",
          "% Piloto Automático": "2,80%",
          "Eco-Roll/I-Roll": "02:36:27",
          "% Eco-Roll/I-Roll": "1,45%",
          "Uso do Pedal Ideal": "79:13:16",
          "% Pedal Ideal": "73,58%",
          "Uso do Pedal Atenção": "09:43:25",
          "% Pedal Atenção": "9,03%",
          "Uso do Pedal Critico": "18:42:55",
          "% Pedal Critico": "17,38%"
        },
        {
          "Frota": "289",
          "Placa": "TTY5D31",
          "Marca": "DAF",
          "Modelo": "XF FTT EURO 6",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "54",
          "Km Total": "6954,25",
          "Velocidade Média": "43,87",
          "Consumo Total": "3412,5",
          "Média computador de bordo": "2,04",
          "Odômetro": "23953,26",
          "Freadas em Alta velocidade": "25",
          "Freadas totais": "420",
          "Freadas a cada 100 km": "6",
          "Total Motor Ligado Parado": "51:23:39",
          "% Total Motor Ligado Parado": "24,48%",
          "Tempo em Movimento": "158:32:10",
          "% Tempo em Movimento": "75,52%",
          "Faixa Verde": "150:06:28",
          "% Faixa Verde": "94,68%",
          "Início da faixa verde": "135:12:30",
          "% Início da faixa verde": "85,29%",
          "Final da faixa verde": "14:53:58",
          "% Final da faixa verde": "9,40%",
          "Acelerando acima do verde": "01:54:43",
          "% Acelerando acima do verde": "1,21%",
          "Aproveitamento de Embalo": "49:24:21",
          "% Aproveitamento de Embalo": "31,16%",
          "Excesso de Velocidade": "00:56:58",
          "% Excesso de Velocidade": "0,60%",
          "Freio Motor": "06:32:58",
          "% Freio Motor": "4,13%",
          "Piloto Automático": "07:09:10",
          "% Piloto Automático": "4,51%",
          "Eco-Roll/I-Roll": "02:24:31",
          "% Eco-Roll/I-Roll": "1,52%",
          "Uso do Pedal Ideal": "75:52:40",
          "% Pedal Ideal": "73,27%",
          "Uso do Pedal Atenção": "07:58:03",
          "% Pedal Atenção": "7,69%",
          "Uso do Pedal Critico": "19:42:49",
          "% Pedal Critico": "19,04%"
        },
        {
          "Frota": "290",
          "Placa": "TTX5E12",
          "Marca": "DAF",
          "Modelo": "XF FTT EURO 6",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "57",
          "Km Total": "6337,4",
          "Velocidade Média": "43,1",
          "Consumo Total": "3123,5",
          "Média computador de bordo": "2,03",
          "Odômetro": "25071,94",
          "Freadas em Alta velocidade": "7",
          "Freadas totais": "360",
          "Freadas a cada 100 km": "5,7",
          "Total Motor Ligado Parado": "49:41:34",
          "% Total Motor Ligado Parado": "25,25%",
          "Tempo em Movimento": "147:04:45",
          "% Tempo em Movimento": "74,75%",
          "Faixa Verde": "137:10:34",
          "% Faixa Verde": "93,27%",
          "Início da faixa verde": "122:11:03",
          "% Início da faixa verde": "83,07%",
          "Final da faixa verde": "15:00:01",
          "% Final da faixa verde": "10,20%",
          "Acelerando acima do verde": "03:06:40",
          "% Acelerando acima do verde": "2,12%",
          "Aproveitamento de Embalo": "47:57:42",
          "% Aproveitamento de Embalo": "32,61%",
          "Excesso de Velocidade": "00:36:27",
          "% Excesso de Velocidade": "0,41%",
          "Freio Motor": "06:50:00",
          "% Freio Motor": "4,65%",
          "Piloto Automático": "45:23:21",
          "% Piloto Automático": "30,86%",
          "Eco-Roll/I-Roll": "02:54:01",
          "% Eco-Roll/I-Roll": "1,97%",
          "Uso do Pedal Ideal": "46:24:03",
          "% Pedal Ideal": "81,79%",
          "Uso do Pedal Atenção": "03:46:57",
          "% Pedal Atenção": "6,67%",
          "Uso do Pedal Critico": "06:32:43",
          "% Pedal Critico": "11,54%"
        },
        {
          "Frota": "292",
          "Placa": "TTX5A80",
          "Marca": "DAF",
          "Modelo": "XF FTT EURO 6",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "35",
          "Km Total": "7278,84",
          "Velocidade Média": "45,57",
          "Consumo Total": "3692",
          "Média computador de bordo": "1,97",
          "Odômetro": "19984,48",
          "Freadas em Alta velocidade": "59",
          "Freadas totais": "601",
          "Freadas a cada 100 km": "8,3",
          "Total Motor Ligado Parado": "47:44:25",
          "% Total Motor Ligado Parado": "23,01%",
          "Tempo em Movimento": "159:44:25",
          "% Tempo em Movimento": "76,99%",
          "Faixa Verde": "154:02:07",
          "% Faixa Verde": "96,43%",
          "Início da faixa verde": "126:52:51",
          "% Início da faixa verde": "79,43%",
          "Final da faixa verde": "27:09:16",
          "% Final da faixa verde": "17,00%",
          "Acelerando acima do verde": "01:08:34",
          "% Acelerando acima do verde": "0,72%",
          "Aproveitamento de Embalo": "50:47:49",
          "% Aproveitamento de Embalo": "31,80%",
          "Excesso de Velocidade": "03:05:07",
          "% Excesso de Velocidade": "1,93%",
          "Freio Motor": "04:36:13",
          "% Freio Motor": "2,88%",
          "Piloto Automático": "05:12:43",
          "% Piloto Automático": "3,26%",
          "Eco-Roll/I-Roll": "02:47:04",
          "% Eco-Roll/I-Roll": "1,74%",
          "Uso do Pedal Ideal": "72:25:25",
          "% Pedal Ideal": "69,24%",
          "Uso do Pedal Atenção": "07:52:43",
          "% Pedal Atenção": "7,53%",
          "Uso do Pedal Critico": "24:17:52",
          "% Pedal Critico": "23,23%"
        },
        {
          "Frota": "293",
          "Placa": "TTX5A81",
          "Marca": "DAF",
          "Modelo": "XF FTT EURO 6",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "65",
          "Km Total": "0,44",
          "Velocidade Média": "4,39",
          "Consumo Total": "1,5",
          "Média computador de bordo": "0,29",
          "Odômetro": "15221,29",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "0",
          "Freadas a cada 100 km": "0",
          "Total Motor Ligado Parado": "00:08:01",
          "% Total Motor Ligado Parado": "57,15%",
          "Tempo em Movimento": "00:06:01",
          "% Tempo em Movimento": "42,85%",
          "Faixa Verde": "00:06:01",
          "% Faixa Verde": "100,00%",
          "Início da faixa verde": "00:06:01",
          "% Início da faixa verde": "100,00%",
          "Final da faixa verde": "00:00:00",
          "% Final da faixa verde": "0,00%",
          "Acelerando acima do verde": "00:00:00",
          "% Acelerando acima do verde": "0,00%",
          "Aproveitamento de Embalo": "00:02:30",
          "% Aproveitamento de Embalo": "41,53%",
          "Excesso de Velocidade": "00:00:00",
          "% Excesso de Velocidade": "0,00%",
          "Freio Motor": "00:00:00",
          "% Freio Motor": "0,00%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:00:00",
          "% Eco-Roll/I-Roll": "0,00%",
          "Uso do Pedal Ideal": "00:01:00",
          "% Pedal Ideal": "28,44%",
          "Uso do Pedal Atenção": "00:00:00",
          "% Pedal Atenção": "0,00%",
          "Uso do Pedal Critico": "00:02:31",
          "% Pedal Critico": "71,66%"
        },
        {
          "Frota": "291",
          "Placa": "TTC8J52",
          "Marca": "DAF",
          "Modelo": "XF FTT EURO 6",
          "Tração": "6X4",
          "Grupo de Veículos": "Rodoviário",
          "Nota Geral": "71",
          "Km Total": "7880,8",
          "Velocidade Média": "40,22",
          "Consumo Total": "3816,5",
          "Média computador de bordo": "2,06",
          "Odômetro": "16915,34",
          "Freadas em Alta velocidade": "41",
          "Freadas totais": "610",
          "Freadas a cada 100 km": "7,7",
          "Total Motor Ligado Parado": "39:57:15",
          "% Total Motor Ligado Parado": "16,94%",
          "Tempo em Movimento": "195:58:07",
          "% Tempo em Movimento": "83,06%",
          "Faixa Verde": "191:42:34",
          "% Faixa Verde": "97,83%",
          "Início da faixa verde": "172:09:13",
          "% Início da faixa verde": "87,85%",
          "Final da faixa verde": "19:33:21",
          "% Final da faixa verde": "9,98%",
          "Acelerando acima do verde": "00:43:58",
          "% Acelerando acima do verde": "0,37%",
          "Aproveitamento de Embalo": "69:47:19",
          "% Aproveitamento de Embalo": "35,61%",
          "Excesso de Velocidade": "00:56:31",
          "% Excesso de Velocidade": "0,48%",
          "Freio Motor": "03:33:34",
          "% Freio Motor": "1,82%",
          "Piloto Automático": "00:07:31",
          "% Piloto Automático": "0,06%",
          "Eco-Roll/I-Roll": "03:42:13",
          "% Eco-Roll/I-Roll": "1,89%",
          "Uso do Pedal Ideal": "95:09:09",
          "% Pedal Ideal": "74,64%",
          "Uso do Pedal Atenção": "10:15:25",
          "% Pedal Atenção": "8,05%",
          "Uso do Pedal Critico": "22:03:49",
          "% Pedal Critico": "17,31%"
        },
        {
          "Frota": "173",
          "Placa": "KNW2J38",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/13.180",
          "Tração": "6X2",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Nota Geral": "0",
          "Km Total": "3914,25",
          "Velocidade Média": "48,26",
          "Consumo Total": "711",
          "Média computador de bordo": "5,51",
          "Odômetro": "812518,92",
          "Freadas em Alta velocidade": "2",
          "Freadas totais": "22",
          "Freadas a cada 100 km": "0,6",
          "Total Motor Ligado Parado": "16:48:31",
          "% Total Motor Ligado Parado": "17,16%",
          "Tempo em Movimento": "81:09:04",
          "% Tempo em Movimento": "82,84%",
          "Faixa Verde": "61:10:01",
          "% Faixa Verde": "75,37%",
          "Início da faixa verde": "43:38:22",
          "% Início da faixa verde": "53,78%",
          "Final da faixa verde": "17:31:39",
          "% Final da faixa verde": "21,60%",
          "Acelerando acima do verde": "17:24:42",
          "% Acelerando acima do verde": "21,46%",
          "Aproveitamento de Embalo": "25:24:16",
          "% Aproveitamento de Embalo": "31,31%",
          "Excesso de Velocidade": "05:26:58",
          "% Excesso de Velocidade": "6,72%",
          "Freio Motor": "02:34:28",
          "% Freio Motor": "3,17%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:01:36",
          "% Eco-Roll/I-Roll": "0,03%",
          "Uso do Pedal Ideal": "24:02:09",
          "% Pedal Ideal": "42,86%",
          "Uso do Pedal Atenção": "14:23:34",
          "% Pedal Atenção": "25,67%",
          "Uso do Pedal Critico": "17:38:58",
          "% Pedal Critico": "31,47%"
        },
        {
          "Frota": "172",
          "Placa": "LLA8G50",
          "Marca": "VOLKSWAGEN",
          "Modelo": "VW/24.250 CLC",
          "Tração": "6X2",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Nota Geral": "5",
          "Km Total": "5202,74",
          "Velocidade Média": "50,64",
          "Consumo Total": "1331,64",
          "Média computador de bordo": "3,91",
          "Odômetro": "890018,95",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "0",
          "Freadas a cada 100 km": "0",
          "Total Motor Ligado Parado": "35:58:19",
          "% Total Motor Ligado Parado": "25,92%",
          "Tempo em Movimento": "102:48:28",
          "% Tempo em Movimento": "74,08%",
          "Faixa Verde": "89:43:09",
          "% Faixa Verde": "87,27%",
          "Início da faixa verde": "63:41:28",
          "% Início da faixa verde": "61,95%",
          "Final da faixa verde": "26:02:10",
          "% Final da faixa verde": "25,33%",
          "Acelerando acima do verde": "05:39:01",
          "% Acelerando acima do verde": "5,50%",
          "Aproveitamento de Embalo": "33:52:28",
          "% Aproveitamento de Embalo": "32,95%",
          "Excesso de Velocidade": "09:51:13",
          "% Excesso de Velocidade": "9,58%",
          "Freio Motor": "03:12:40",
          "% Freio Motor": "3,12%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:19:31",
          "% Eco-Roll/I-Roll": "0,32%",
          "Uso do Pedal Ideal": "42:07:46",
          "% Pedal Ideal": "58,44%",
          "Uso do Pedal Atenção": "13:34:21",
          "% Pedal Atenção": "18,83%",
          "Uso do Pedal Critico": "16:23:22",
          "% Pedal Critico": "22,73%"
        },
        {
          "Frota": "203",
          "Placa": "LLO1333",
          "Marca": "SCANIA",
          "Modelo": "SCANIA/P 340",
          "Tração": "4X2",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Nota Geral": "84",
          "Km Total": "1086,52",
          "Velocidade Média": "27,57",
          "Consumo Total": "636",
          "Média computador de bordo": "1,71",
          "Odômetro": "668282,15",
          "Freadas em Alta velocidade": "0",
          "Freadas totais": "218",
          "Freadas a cada 100 km": "20,1",
          "Total Motor Ligado Parado": "19:15:04",
          "% Total Motor Ligado Parado": "32,82%",
          "Tempo em Movimento": "39:24:40",
          "% Tempo em Movimento": "67,18%",
          "Faixa Verde": "39:45:13",
          "% Faixa Verde": "100,00%",
          "Início da faixa verde": "37:36:39",
          "% Início da faixa verde": "95,43%",
          "Final da faixa verde": "02:08:34",
          "% Final da faixa verde": "5,44%",
          "Acelerando acima do verde": "00:04:58",
          "% Acelerando acima do verde": "0,21%",
          "Aproveitamento de Embalo": "16:10:25",
          "% Aproveitamento de Embalo": "41,04%",
          "Excesso de Velocidade": "00:01:31",
          "% Excesso de Velocidade": "0,06%",
          "Freio Motor": "00:00:30",
          "% Freio Motor": "0,02%",
          "Piloto Automático": "01:08:05",
          "% Piloto Automático": "2,88%",
          "Eco-Roll/I-Roll": "00:51:51",
          "% Eco-Roll/I-Roll": "2,19%",
          "Uso do Pedal Ideal": "21:02:16",
          "% Pedal Ideal": "92,90%",
          "Uso do Pedal Atenção": "00:57:22",
          "% Pedal Atenção": "4,22%",
          "Uso do Pedal Critico": "00:39:04",
          "% Pedal Critico": "2,88%"
        },
        {
          "Frota": "238",
          "Placa": "KPD6B43",
          "Marca": "VOLVO",
          "Modelo": "VOLVO/VM 270",
          "Tração": "6X2",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Nota Geral": "51",
          "Km Total": "1294,15",
          "Velocidade Média": "40,16",
          "Consumo Total": "296,5",
          "Média computador de bordo": "4,36",
          "Odômetro": "471389,74",
          "Freadas em Alta velocidade": "3",
          "Freadas totais": "308",
          "Freadas a cada 100 km": "23,8",
          "Total Motor Ligado Parado": "11:37:00",
          "% Total Motor Ligado Parado": "26,50%",
          "Tempo em Movimento": "32:13:28",
          "% Tempo em Movimento": "73,50%",
          "Faixa Verde": "27:44:49",
          "% Faixa Verde": "86,10%",
          "Início da faixa verde": "24:22:28",
          "% Início da faixa verde": "75,64%",
          "Final da faixa verde": "03:22:21",
          "% Final da faixa verde": "10,47%",
          "Acelerando acima do verde": "03:28:07",
          "% Acelerando acima do verde": "10,76%",
          "Aproveitamento de Embalo": "14:04:54",
          "% Aproveitamento de Embalo": "43,70%",
          "Excesso de Velocidade": "00:10:01",
          "% Excesso de Velocidade": "0,52%",
          "Freio Motor": "01:04:01",
          "% Freio Motor": "3,31%",
          "Piloto Automático": "00:00:00",
          "% Piloto Automático": "0,00%",
          "Eco-Roll/I-Roll": "00:17:15",
          "% Eco-Roll/I-Roll": "0,89%",
          "Uso do Pedal Ideal": "14:27:04",
          "% Pedal Ideal": "79,25%",
          "Uso do Pedal Atenção": "01:59:28",
          "% Pedal Atenção": "10,92%",
          "Uso do Pedal Critico": "01:47:31",
          "% Pedal Critico": "9,83%"
        },
        {
          "Frota": "",
          "Placa": "",
          "Marca": "",
          "Modelo": "",
          "Tração": "",
          "Grupo de Veículos": "",
          "Nota Geral": "",
          "Km Total": "",
          "Velocidade Média": "",
          "Consumo Total": "",
          "Média computador de bordo": "",
          "Odômetro": "",
          "Freadas em Alta velocidade": "",
          "Freadas totais": "",
          "Freadas a cada 100 km": "",
          "Total Motor Ligado Parado": "732:48:58",
          "% Total Motor Ligado Parado": "",
          "Tempo em Movimento": "2307:50:19",
          "% Tempo em Movimento": "",
          "Faixa Verde": "2183:38:28",
          "% Faixa Verde": "",
          "Início da faixa verde": "1949:26:12",
          "% Início da faixa verde": "",
          "Final da faixa verde": "234:13:16",
          "% Final da faixa verde": "",
          "Acelerando acima do verde": "62:51:15",
          "% Acelerando acima do verde": "",
          "Aproveitamento de Embalo": "836:32:32",
          "% Aproveitamento de Embalo": "",
          "Excesso de Velocidade": "42:39:52",
          "% Excesso de Velocidade": "",
          "Freio Motor": "56:47:31",
          "% Freio Motor": "",
          "Piloto Automático": "77:46:39",
          "% Piloto Automático": "",
          "Eco-Roll/I-Roll": "34:16:34",
          "% Eco-Roll/I-Roll": "",
          "Uso do Pedal Ideal": "1095:40:46",
          "% Pedal Ideal": "",
          "Uso do Pedal Atenção": "115:14:10",
          "% Pedal Atenção": "",
          "Uso do Pedal Critico": "221:19:03",
          "% Pedal Critico": ""
        }
      ]
    },
    {
      "name": "Abril",
      "sourceName": "Abril",
      "gid": "1046930752",
      "order": 4,
      "type": null,
      "rows": []
    },
    {
      "name": "Maio",
      "sourceName": "Maio",
      "gid": "79362452",
      "order": 5,
      "type": null,
      "rows": []
    },
    {
      "name": "Junho",
      "sourceName": "Junho",
      "gid": "967342850",
      "order": 6,
      "type": null,
      "rows": []
    },
    {
      "name": "Julho",
      "sourceName": "Julho",
      "gid": "303673235",
      "order": 7,
      "type": null,
      "rows": []
    },
    {
      "name": "Agosto",
      "sourceName": "Agosto",
      "gid": "1720965887",
      "order": 8,
      "type": null,
      "rows": []
    },
    {
      "name": "Setembro",
      "sourceName": "Setembro",
      "gid": "993423638",
      "order": 9,
      "type": null,
      "rows": []
    },
    {
      "name": "Outubro",
      "sourceName": "Outubro",
      "gid": "842319723",
      "order": 10,
      "type": null,
      "rows": []
    },
    {
      "name": "Novembro",
      "sourceName": "Novembro",
      "gid": "163450483",
      "order": 11,
      "type": null,
      "rows": []
    },
    {
      "name": "Dezembro",
      "sourceName": "Dezembro",
      "gid": "698561355",
      "order": 12,
      "type": null,
      "rows": []
    },
    {
      "name": "Meta",
      "sourceName": "Meta",
      "gid": "1218984725",
      "order": 99,
      "type": "meta",
      "rows": [
        {
          "Frota": "150",
          "Placa": "KNM9F91",
          "Modelo": "SCANIA/G 420",
          "Grupo de Veículos": "Operação Redex",
          "Meta": "1,9"
        },
        {
          "Frota": "171",
          "Placa": "LKZ8C47",
          "Modelo": "SCANIA/P 310",
          "Grupo de Veículos": "Operação Vazio",
          "Meta": "2,5"
        },
        {
          "Frota": "172",
          "Placa": "LLA8G50",
          "Modelo": "VW/24.250 CLC",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Meta": "4"
        },
        {
          "Frota": "173",
          "Placa": "KNW2J38",
          "Modelo": "VW/13.180",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Meta": "4"
        },
        {
          "Frota": "177",
          "Placa": "KZK2E10",
          "Modelo": "SCANIA/R 420",
          "Grupo de Veículos": "Operação Redex",
          "Meta": "2,8"
        },
        {
          "Frota": "181",
          "Placa": "LLI2F10",
          "Modelo": "VW/19.320",
          "Grupo de Veículos": "Operação Vazio",
          "Meta": "2,5"
        },
        {
          "Frota": "188",
          "Placa": "LPT9A89",
          "Modelo": "SCANIA/R 420",
          "Grupo de Veículos": "Operação Redex",
          "Meta": "2,8"
        },
        {
          "Frota": "190",
          "Placa": "KVJ9G66",
          "Modelo": "SCANIA/R 420",
          "Grupo de Veículos": "Operação Redex",
          "Meta": "2,8"
        },
        {
          "Frota": "203",
          "Placa": "LLO1333",
          "Modelo": "SCANIA/P 340",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Meta": "2,5"
        },
        {
          "Frota": "222",
          "Placa": "KOW6F24",
          "Modelo": "VW/24.250 CNC",
          "Grupo de Veículos": "OPERAÇÃO MUNCK",
          "Meta": "3,5"
        },
        {
          "Frota": "227",
          "Placa": "LLT6B06",
          "Modelo": "VW/19.330 CTC",
          "Grupo de Veículos": "Operação Vazio",
          "Meta": "2,5"
        },
        {
          "Frota": "229",
          "Placa": "LLT6B02",
          "Modelo": "VW/19.330 CTC",
          "Grupo de Veículos": "Operação Vazio",
          "Meta": "2,5"
        },
        {
          "Frota": "230",
          "Placa": "LQN4F96",
          "Modelo": "VW/19.330 CTC",
          "Grupo de Veículos": "Operação Vazio",
          "Meta": "2,5"
        },
        {
          "Frota": "231",
          "Placa": "LRA1E88",
          "Modelo": "SCANIA/R 440",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "2,8"
        },
        {
          "Frota": "236",
          "Placa": "KWC5138",
          "Modelo": "SCANIA/P 360",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "2,5"
        },
        {
          "Frota": "238",
          "Placa": "KPD6B43",
          "Modelo": "VOLVO/VM 270",
          "Grupo de Veículos": "XZ TRANSPORTES",
          "Meta": "3"
        },
        {
          "Frota": "243",
          "Placa": "LSE9F88",
          "Modelo": "SCANIA/P 360",
          "Grupo de Veículos": "Operação Baker",
          "Meta": "2,5"
        },
        {
          "Frota": "244",
          "Placa": "KRH8082",
          "Modelo": "SCANIA/P 360",
          "Grupo de Veículos": "Operação Baker",
          "Meta": "2,5"
        },
        {
          "Frota": "245",
          "Placa": "KWW9A65",
          "Modelo": "SCANIA/P 360",
          "Grupo de Veículos": "Operação Baker",
          "Meta": "2,5"
        },
        {
          "Frota": "246",
          "Placa": "LSE9591",
          "Modelo": "SCANIA/P 360",
          "Grupo de Veículos": "Operação Baker",
          "Meta": "2,5"
        },
        {
          "Frota": "247",
          "Placa": "LSF8B12",
          "Modelo": "SCANIA/R 480",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "284",
          "Placa": "TTC9B61",
          "Modelo": "XF FTS EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "285",
          "Placa": "TTX5D85",
          "Modelo": "XF FTS EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "286",
          "Placa": "TTU6J59",
          "Modelo": "XF FTS EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "287",
          "Placa": "TTY5A07",
          "Modelo": "XF FTS EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "288",
          "Placa": "TUL2J59",
          "Modelo": "XF FTS EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "289",
          "Placa": "TTY5D31",
          "Modelo": "XF FTT EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "290",
          "Placa": "TTX5E12",
          "Modelo": "XF FTT EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "291",
          "Placa": "TTC8J52",
          "Modelo": "XF FTT EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "292",
          "Placa": "TTX5A80",
          "Modelo": "XF FTT EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        },
        {
          "Frota": "293",
          "Placa": "TTX5A81",
          "Modelo": "XF FTT EURO 6",
          "Grupo de Veículos": "Rodoviário",
          "Meta": "1,9"
        }
      ]
    },
    {
      "name": "Motorista por veiculo",
      "sourceName": "Motorista por veiculo",
      "gid": "1093491459",
      "order": 100,
      "type": "motorista",
      "rows": [
        {
          "Frota": "150",
          "Placa": "KNM9F91",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "171",
          "Placa": "LKZ8C47",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "172",
          "Placa": "LLA8G50",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "173",
          "Placa": "KNW2J38",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "177",
          "Placa": "KZK2E10",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "181",
          "Placa": "LLI2F10",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "188",
          "Placa": "LPT9A89",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "190",
          "Placa": "KVJ9G66",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "203",
          "Placa": "LLO1333",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "222",
          "Placa": "KOW6F24",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "227",
          "Placa": "LLT6B06",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "229",
          "Placa": "LLT6B02",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "230",
          "Placa": "LQN4F96",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "231",
          "Placa": "LRA1E88",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "236",
          "Placa": "KWC5138",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "238",
          "Placa": "KPD6B43",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "243",
          "Placa": "LSE9F88",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "244",
          "Placa": "KRH8082",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "245",
          "Placa": "KWW9A65",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "246",
          "Placa": "LSE9591",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "247",
          "Placa": "LSF8B12",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "284",
          "Placa": "TTC9B61",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "285",
          "Placa": "TTX5D85",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "286",
          "Placa": "TTU6J59",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "287",
          "Placa": "TTY5A07",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "288",
          "Placa": "TUL2J59",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "289",
          "Placa": "TTY5D31",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "290",
          "Placa": "TTX5E12",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "291",
          "Placa": "TTC8J52",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "292",
          "Placa": "TTX5A80",
          "Motorista": "Genival Silva"
        },
        {
          "Frota": "293",
          "Placa": "TTX5A81",
          "Motorista": "Genival Silva"
        }
      ]
    }
  ]
};
